### ISSUE TITLE
EU_CENTRAL_1 not found in SQS.apply()

### ISSUE THREAD

**Issue by jcbarton** [seratch/AWScala#79] opened 2015-05-07 15:34 UTC
Hi,

We're currently using 0.5.2. We were using an older version (0.3.x) before, and this code worked, so something somewhere has changed! 

Here is the code:

implicit val sqs = SQS.apply(<key>, <secret>)(Region.Ireland)

This is the error:
java.lang.NoSuchFieldError: EU_CENTRAL_1
        awscala.Region0$.<init>(Region0.scala:27)
        awscala.Region0$.<clinit>(Region0.scala)
        awscala.package$.<init>(package.scala:3)
        awscala.package$.<clinit>(package.scala)

Any clues?

**Comment by seratch** [comment] 2015-05-31 23:09
I'm not sure but I couldn't reproduce your issue.

```
scala> import awscala._, sqs._
import awscala._
import sqs._

scala> implicit val sqs = SQS.at(Region.Tokyo)
sqs: awscala.sqs.SQS = awscala.sqs.SQSClient@1b4ef27

scala> implicit val sqs = SQS.at(Region.Ireland)
sqs: awscala.sqs.SQS = awscala.sqs.SQSClient@49a0f01e
```

**Comment by biomunky** [comment] 2015-06-05 14:11
I noticed the same thing. Everything is fine in sbt console but something was up with the assembly.

**Comment by zzztimbo** [comment] 2015-06-10 19:50
I get the same error when trying to obtain an S3 object.

java.lang.NoSuchFieldError: EU_CENTRAL_1
	at awscala.Region0$.<init>(Region0.scala:27)
	at awscala.Region0$.<clinit>(Region0.scala)
	at awscala.package$.<init>(package.scala:3)
	at awscala.package$.<clinit>(package.scala)

**Comment by malachheb** [comment] 2015-09-01 08:31
I had the same problem using aws-sdk-java 1.10.14 with 1.10.13 i have not the problem

**Comment by malachheb** [comment] 2015-09-06 18:16
another way to initialise object using amazonaws package directly: 
`  implicit val sqs = SQS.at(com.amazonaws.regions.Region.getRegion(com.amazonaws.regions.Regions.EU_WEST_1)) `

**Comment by coolamazone** [comment] 2016-01-27 13:38
I am using 0.4.2 version. It's showing this error

Exception in thread "main" java.lang.NoSuchFieldError: EU_CENTRAL_1
        at awscala.Region$.<init>(Region.scala:27)
        at awscala.Region$.<clinit>(Region.scala)
        at com.touchtalent.bobbleapp.spark.sql.scala.repository.DynamoDB$.<init>(DynamoDB.scala:19)
        at com.touchtalent.bobbleapp.spark.sql.scala.repository.DynamoDB$.<clinit>(DynamoDB.scala)

**Comment by czyuto** [comment] 2016-06-08 13:19
I get the same error at 0.5 version.
```
val s3 = S3.at(Region.Tokyo)
val s3 = S3.at(Region.AP_NORTHEAST_1)
```

```
java.lang.NoSuchFieldError: EU_CENTRAL_1
        at awscala.Region0$.<init>(Region0.scala:27)
        at awscala.Region0$.<clinit>(Region0.scala)
        at awscala.package$.<init>(package.scala:3)
        at awscala.package$.<clinit>(package.scala)
```

**Comment by moc-yuto** [comment] 2016-06-08 13:22
I get the same error at 0.5 version.
```
val s3 = S3.at(Region.Tokyo)
val s3 = S3.at(Region.AP_NORTHEAST_1)
```

```
java.lang.NoSuchFieldError: EU_CENTRAL_1
        at awscala.Region0$.<init>(Region0.scala:27)
        at awscala.Region0$.<clinit>(Region0.scala)
        at awscala.package$.<init>(package.scala:3)
        at awscala.package$.<clinit>(package.scala)
```

**Comment by seratch** [comment] 2016-06-08 13:28
I'm afraid that you guys here are using AWScala with some imcompatible AWS SDK version. Check your libraryDependencies. https://github.com/seratch/AWScala/blob/master/project/Build.scala#L6

**Comment by moc-yuto** [comment] 2016-06-08 15:08
The Error caused by aws-java-sdk 1.8.6 being installed at sbt compile in my project by another library..
```
[info] Resolving com.amazonaws#aws-java-sdk;1.8.6 ...
```

**Comment by seratch** [comment] 2016-06-08 15:30
Try `dependencyOverrides`!

**Comment by moc-yuto** [comment] 2016-06-09 01:05
Thx! 👍

**Comment by seratch** [comment] 2016-06-09 01:16
The cause of the problem this issue points is due to AWS SDK bin-incompatibility. You must use AWS SDK 1.10.x for AWScala 0.5.x. IMO, we don't have any actions to do for this issue. Let me close this.

**Closed by seratch** 2016-06-09 01:16 UTC
